### ISSUE TITLE
add mapping yaml file creation

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pySMWsync#5]
```yaml
- topic: Volume
  prop_list:
  - smw_prop: number
    pid: P?
    arg: number
    pid_label: null
  - smw_prop: title
    pid: P?
    arg: title
    pid_label: null
- topic: Session
  prop_list:
  - smw_prop: title
    pid: P?
    arg: title
    pid_label: null
- topic: Paper
  prop_list:
  - smw_prop: id
    pid: P?
    arg: id
    pid_label: null
  - smw_prop: title
    pid: P?
    arg: title
    pid_label: null
  - smw_prop: authors
    pid: P?
    arg: authors
    pid_label: null
  - smw_prop: pdfUrl
    pid: P?
    arg: pdfUrl
    pid_label: null
```
